export const TOGGLE_CHAT = "BEHAVIOR/TOGGLE_CHAT";
export const SELECTED_TAB = "BEHAVIOR/SELECTED_TAB";
export const GET_CARDS = "CARD/GET_CARDS";
export const TOGGLE_MODAL = "CARD/TOGGLE_MODAL";
export const MODAL_DATA = "CARD/MODAL_DATA";
export const SEARCH_TEXT = "CARD/SEARCH_TEXT";
export const TOGGLE_LOADING = "CARD/TOGGLE_LOADING";
export const CHANGE_TEXT = "CARD/CHANGE_TEXT";
